[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[dependencies]
genai = "0.1.22"
tokio = { version = "1.27.0", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
futures = "0.3.28"
